// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDylxEc3ieZ9sRfsw4yefk74CIFLGHM2qs',
    appId: '1:248978859141:web:440259482ef7239a8335ec',
    messagingSenderId: '248978859141',
    projectId: 'sharp-ff38b',
    authDomain: 'sharp-ff38b.firebaseapp.com',
    databaseURL: 'https://sharp-ff38b-default-rtdb.firebaseio.com',
    storageBucket: 'sharp-ff38b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmzhKjrKj8toaPyz8HPKyCMPDT60sJ4zg',
    appId: '1:248978859141:android:b0a167f1e36e8d448335ec',
    messagingSenderId: '248978859141',
    projectId: 'sharp-ff38b',
    databaseURL: 'https://sharp-ff38b-default-rtdb.firebaseio.com',
    storageBucket: 'sharp-ff38b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPphaaeEwEj6dsiiKSkYwX6lmIHwWfGW0',
    appId: '1:248978859141:ios:5bb7583741ed05238335ec',
    messagingSenderId: '248978859141',
    projectId: 'sharp-ff38b',
    databaseURL: 'https://sharp-ff38b-default-rtdb.firebaseio.com',
    storageBucket: 'sharp-ff38b.appspot.com',
    iosClientId: '248978859141-m0kh9m2ffhtbvlsuuoqlg3ol4ahnabmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPphaaeEwEj6dsiiKSkYwX6lmIHwWfGW0',
    appId: '1:248978859141:ios:5bb7583741ed05238335ec',
    messagingSenderId: '248978859141',
    projectId: 'sharp-ff38b',
    databaseURL: 'https://sharp-ff38b-default-rtdb.firebaseio.com',
    storageBucket: 'sharp-ff38b.appspot.com',
    iosClientId: '248978859141-m0kh9m2ffhtbvlsuuoqlg3ol4ahnabmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharp',
  );
}
